---
title: "Labo 1"
author: "Oscar Centeno Mora - IAM"
date: ""
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plotly)
library(DT)
library(ggplot2)
library(forecast)
library(tidyverse)
library(date)
library(lubridate)
library(xts)        # To make the convertion data-frame / xts format
library(dygraphs)
library(ggExtra)
library(plotly)
library(gapminder)
library(gridExtra)
library(rattle)
library(ggridges)
library(vioplot)
library(likert)
library(fmsb) 
library(wordcloud)
library(reshape)
library(tm)
library(GGally)
library(car)
library(RColorBrewer)
library(ellipse)
library(corrgram)
library(treemap)
library(d3Tree)
library(dendextend)
library(ggraph)
library(igraph)
library(networkD3)
library(circlize)
library(ggmap)
library(cartography)
library(maps)
library(geosphere)
library(DT)
library(kableExtra)
library(formattable)
library(digest)
library(devtools)


```

<style>
table {
background-color:#FFFFFF;
}
</style>

<style>
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: darkblue;
}
</style>

<button onclick="document.body.scrollTop = document.documentElement.scrollTop = 0;" style="
    position: fixed;
    bottom: 5px;
    right: 40px;
    text-align: center;
    cursor: pointer;
    outline: none;
    color: #fff;
    background-color: #0A71A0;
    border: none;
    border-radius: 15px;
    
">Ir arriba</button>


# HIERARCHICAL EDGE BUNDLING {.tabset .tabset-fade .tabset-pills}

## Gráficos multivariados {.tabset .tabset-fade}

### Hirarchical edge bundling interactivo

#### Algunos  Hierarchical edge bundling


```{r echo=FALSE, error=FALSE ,message=FALSE, warning=FALSE}
d1=data.frame(from="origin", to=paste("group", seq(1,10), sep=""))
d2=data.frame(from=rep(d1$to, each=10), to=paste("subgroup", seq(1,100), sep="_"))
hierarchy=rbind(d1, d2)

vertices = data.frame(name = unique(c(as.character(hierarchy$from), as.character(hierarchy$to))) ) 
```

```{r echo=FALSE, error=FALSE ,message=FALSE, warning=FALSE}

# Create a graph object with the igraph library
mygraph <- graph_from_data_frame( hierarchy, vertices=vertices )
# This is a network object, you visualize it as a network like shown in the network section!
 

```

```{r echo=FALSE, error=FALSE ,message=FALSE, warning=FALSE}
ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_edge_diagonal(alpha=0.1) +
  geom_conn_bundle(data = get_con(from = c(18,20,30), to = c(19, 50, 70)), alpha=1, width=1, colour="skyblue", tension = 0) +
  theme_void()
 
ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_edge_diagonal(alpha=0.1) +
  geom_conn_bundle(data = get_con(from = c(18,20,30), to = c(19, 50, 70)), alpha=1, width=1, colour="skyblue", tension = 1) +
  theme_void()

```


```{r echo=FALSE, error=FALSE ,message=FALSE, warning=FALSE}

 # create a dataframe with connection between leaves (individuals)
all_leaves=paste("subgroup", seq(1,100), sep="_")
connect=rbind( data.frame( from=sample(all_leaves, 100, replace=T) , to=sample(all_leaves, 100, replace=T)), data.frame( from=sample(head(all_leaves), 30, replace=T) , to=sample( tail(all_leaves), 30, replace=T)), data.frame( from=sample(all_leaves[25:30], 30, replace=T) , to=sample( all_leaves[55:60], 30, replace=T)), data.frame( from=sample(all_leaves[75:80], 30, replace=T) , to=sample( all_leaves[55:60], 30, replace=T)) )
 
# The connection object must refer to the ids of the leaves:
from = match( connect$from, vertices$name)
to = match( connect$to, vertices$name)

# plot
ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_conn_bundle(data = get_con(from = from, to = to), alpha=0.2, colour="skyblue", tension = 0.9) + 
  geom_node_point(aes(filter = leaf, x = x*1.05, y=y*1.05)) +
  theme_void()

```

Más referencias:

https://www.r-graph-gallery.com/hierarchical-edge-bundling/


