---
title: "Netword analysis"
author: "Oscar Centeno Mora"
date: "21 de junio de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(network)
library(tidyverse)
library(igraph)
library(tidygraph)
library(ggraph)
library(visNetwork)
library(networkD3)
```

```{r}
edge_list <- tibble(from = c(1, 2, 2, 3, 4), to = c(2, 3, 4, 2, 1))
node_list <- tibble(id = 1:4)

edge_list
```

```{r echo=TRUE, warning=FALSE, error=FALSE}
setwd("C:/Users/oscar.centeno/Desktop/IAM/Social Network")

letters <- read.csv2("C:/Users/oscar.centeno/Desktop/IAM/Social Network/correspondence-data-1585.csv")
letters

str(letters)
```

```{r}
sources <- letters %>%
  distinct(source) %>%
  rename(label = source)

destinations <- letters %>%
  distinct(destination) %>%
  rename(label = destination)
```

```{r}
nodes <- full_join(sources, destinations, by = "label")
nodes
```

```{r}
nodes <- nodes %>% rowid_to_column("id")
nodes
```

```{r}
per_route <- letters %>%  
  group_by(source, destination) %>%
  summarise(weight = n()) %>% 
  ungroup()
per_route
```

```{r}
edges <- per_route %>% 
  left_join(nodes, by = c("source" = "label")) %>% 
  rename(from = id)

edges <- edges %>% 
  left_join(nodes, by = c("destination" = "label")) %>% 
  rename(to = id)
```

```{r}
edges <- select(edges, from, to, weight)
edges
```


# Network

```{r}
routes_network <- network(edges, vertex.attr = nodes, matrix.type = "edgelist", ignore.eval = FALSE)

class(routes_network)
routes_network

summary(routes_network)
```

Gráfico de la red

```{r}
#plot(routes_network, vertex.cex = 2)
plot(routes_network, vertex.cex = 3)
#plot(routes_network, vertex.cex = 4)
```

Otras modalidades 

```{r}
plot(routes_network, vertex.cex = 3, mode = "circle")
```


# igraph

Removemos las cosas

```{r}

detach(package:network)
rm(routes_network)

```

```{r}
routes_igraph <- graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE)
routes_igraph

```

```{r}
plot(routes_igraph, edge.arrow.size = 0.2)
```

```{r}
plot(routes_igraph, layout = layout_with_graphopt, edge.arrow.size = 0.2)
```

# tidygraph and ggraph

```{r}
routes_tidy <- tbl_graph(nodes = nodes, edges = edges, directed = TRUE)
```

The second way to create a tbl_graph object is to convert an igraph or network object using as_tbl_graph(). Thus, we could convert routes_igraph to a tbl_graph object.

```{r}
routes_igraph_tidy <- as_tbl_graph(routes_igraph)

class(routes_tidy)
class(routes_igraph_tidy)
class(routes_igraph)
```

```{r}
routes_tidy
summary(routes_tidy)
```


```{r}
routes_tidy %>% 
  activate(edges) %>% 
  arrange(desc(weight))
```

```{r}
ggraph(routes_tidy) + geom_edge_link() + geom_node_point() + theme_graph()
```

```{r}
ggraph(routes_tidy, layout = "graphopt") + 
  geom_node_point() +
  geom_edge_link(aes(width = weight), alpha = 0.8) + 
  scale_edge_width(range = c(0.2, 2)) +
  geom_node_text(aes(label = label), repel = TRUE) +
  labs(edge_width = "Letters") +
  theme_graph()
```


```{r}
ggraph(routes_igraph, layout = "linear") + 
  geom_edge_arc(aes(width = weight), alpha = 0.8) + 
  scale_edge_width(range = c(0.2, 2)) +
  geom_node_text(aes(label = label)) +
  labs(edge_width = "Letters") +
  theme_graph()
```

Interactive network graphs with visNetwork and networkD3

```{r}
visNetwork(nodes, edges)
```

```{r}
edges <- mutate(edges, width = weight/5 + 1)

visNetwork(nodes, edges) %>% 
  visIgraphLayout(layout = "layout_with_fr") %>% 
  visEdges(arrows = "middle")
```

# networkD3

```{r}
nodes_d3 <- mutate(nodes, id = id - 1)
edges_d3 <- mutate(edges, from = from - 1, to = to - 1)
```

```{r}
forceNetwork(Links = edges_d3, Nodes = nodes_d3, Source = "from", Target = "to", 
             NodeID = "label", Group = "id", Value = "weight", 
             opacity = 1, fontSize = 16, zoom = TRUE)
```

```{r}
sankeyNetwork(Links = edges_d3, Nodes = nodes_d3, Source = "from", Target = "to", 
              NodeID = "label", Value = "weight", fontSize = 16, unit = "Letter(s)")
```

